import "./globals.css";

import ClientLayout from "@/app/components/ClientLayout";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Sweat Set App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = async ({ children }) => {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        <ClientLayout session={session}>{children}</ClientLayout>
      </body>
    </html>
  );
};

export default RootLayout;
