import "./globals.css";

import type { Metadata } from "next";
import Nav from "@/app/components/Nav";
import SessionProvider from "@/app/providers/SessionProvider";
// import { ThemeProvider } from "@mui/material/styles";
// import { UserProvider } from "@/app/providers/UserProvider";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
	title: "Sweat Set App",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = async ({ children }) => {
	const session = await getServerSession();

	return (
		<html lang="en">
			<body>
				<SessionProvider session={session}>
					<Nav />
					{children}
				</SessionProvider>
			</body>
		</html>
	);
};

export default RootLayout;
